import { AvevaJsonLoader } from '../rvm/AvevaJsonLoader.js';

export const RVM_STAGEDJSON_LOAD_ADAPTER_SCHEMA = 'rvm-stagedjson-load-adapter/v1';

const INSTALL_FLAG = Symbol.for('pcf-glb-rvm-stagedjson-load-adapter-v1');
const PATCH_FLAG = Symbol.for('pcf-glb-rvm-stagedjson-load-adapter-patched-v1');
const GLOBAL_KEY = '__PCF_GLB_RVM_STAGEDJSON_LOAD_ADAPTER__';
const VERSION = '20260627-rvm-stagedjson-load-adapter-1';
const COORD_KEYS = new Set(['APOS', 'LPOS', 'BPOS', 'POS', 'HPOS', 'TPOS', 'CPOS']);
const SKIP_KEYS = new Set(['children', 'attributes', 'ATTRIBUTES']);
function isObject(value) { return Boolean(value && typeof value === 'object' && !Array.isArray(value)); }
function isStagedJsonDocument(doc) { if (!isObject(doc)) return false; const schema = String(doc.schema || doc.schemaVersion || '').toLowerCase(); if (schema.includes('stagedjson')) return true; if (Array.isArray(doc.branches) || Array.isArray(doc.supportRecords)) return true; if (isObject(doc.model) && (Array.isArray(doc.model.branches) || Array.isArray(doc.model.supportRecords))) return true; return false; }
function stringifyAttr(value) { if (value === undefined || value === null) return undefined; if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') return String(value); try { return JSON.stringify(value); } catch (_) { return String(value); } }
function copyAttributes(record, extra = {}) { const attrs = { ...extra }; const sourceAttrs = isObject(record?.attributes) ? record.attributes : (isObject(record?.ATTRIBUTES) ? record.ATTRIBUTES : {}); for (const [key, value] of Object.entries(sourceAttrs)) { const text = stringifyAttr(value); if (text !== undefined && text !== '') attrs[key] = text; } for (const [key, value] of Object.entries(record || {})) { if (SKIP_KEYS.has(key)) continue; const upper = key.toUpperCase(); if (COORD_KEYS.has(upper)) { attrs[upper] = value; continue; } if (/^[A-Z][A-Z0-9_:-]*$/.test(key) || ['id', 'name', 'type', 'stagedJsonRole', 'primitiveCount'].includes(key)) { const text = stringifyAttr(value); if (text !== undefined && text !== '') attrs[upper === key ? key : upper] = text; } } return attrs; }
function typeOfRecord(record, fallback = 'UNKNOWN') { const value = record?.type || record?.TYPE || record?.attributes?.TYPE || record?.ATTRIBUTES?.TYPE || fallback; const type = String(value || fallback).toUpperCase(); if (type === 'VALV') return 'VALVE'; if (type === 'FLAN') return 'FLANGE'; if (type === 'ELBO') return 'ELBOW'; if (type === 'REDU') return 'REDUCER'; return type || fallback; }
function nameOfRecord(record, fallback = 'Node') { return String(record?.name || record?.NAME || record?.COMPONENT_ID || record?.id || record?.PS_NO || fallback).trim() || fallback; }
function convertComponent(record, index = 0) { const type = typeOfRecord(record, record?.stagedJsonRole === 'support' ? 'SUPPORT' : 'UNKNOWN'); const name = nameOfRecord(record, `${type}-${index + 1}`); return { name, type, attributes: copyAttributes(record, { TYPE: type, NAME: name, SOURCE_FORMAT: 'RVM_STAGEDJSON_SOURCE', STAGEDJSON_ROLE: record?.stagedJsonRole || 'component' }), children: Array.isArray(record?.children) ? record.children.map((child, childIndex) => convertComponent(child, childIndex)) : [] }; }
function convertSupportRecord(record, index = 0) { const name = nameOfRecord(record, `SUPPORT-${index + 1}`); const attrs = copyAttributes(record, { TYPE: 'SUPPORT', NAME: name, SOURCE_FORMAT: 'RVM_STAGEDJSON_SUPPORT_RECORD', STAGEDJSON_ROLE: 'support-record' }); delete attrs.APOS; delete attrs.LPOS; delete attrs.BPOS; delete attrs.POS; return { name, type: 'SUPPORT', attributes: attrs, children: [] }; }
function convertBranch(branch, index = 0) { const name = nameOfRecord(branch, `BRANCH-${index + 1}`); const children = Array.isArray(branch?.children) ? branch.children.map((child, childIndex) => convertComponent(child, childIndex)) : []; return { name, type: 'BRANCH', attributes: copyAttributes(branch, { TYPE: 'BRANCH', NAME: name, SOURCE_FORMAT: 'REV_XML', STAGEDJSON_SOURCE_FORMAT: 'RVM_STAGEDJSON_SOURCE' }), children }; }
function convertStagedJsonToAvevaHierarchy(doc) { const model = isObject(doc.model) ? doc.model : {}; const branches = Array.isArray(doc.branches) ? doc.branches : (Array.isArray(model.branches) ? model.branches : []); const supports = Array.isArray(doc.supportRecords) ? doc.supportRecords : (Array.isArray(model.supportRecords) ? model.supportRecords : []); const modelName = String(model.name || doc.modelName || doc.name || 'StagedJSON Model'); const root = { name: modelName, type: 'GROUP', attributes: { TYPE: 'GROUP', NAME: modelName, SOURCE_FORMAT: 'RVM_STAGEDJSON_SOURCE', STAGEDJSON_SCHEMA: String(doc.schema || doc.schemaVersion || ''), STAGEDJSON_BRANCH_COUNT: String(branches.length), STAGEDJSON_SUPPORT_RECORD_COUNT: String(supports.length) }, children: branches.map((branch, index) => convertBranch(branch, index)) }; if (supports.length) root.children.push({ name: 'Support Records', type: 'GROUP', attributes: { TYPE: 'GROUP', NAME: 'Support Records', SOURCE_FORMAT: 'RVM_STAGEDJSON_SUPPORT_RECORDS', STAGEDJSON_SUPPORT_RECORD_COUNT: String(supports.length) }, children: supports.map((record, index) => convertSupportRecord(record, index)) }); return [root]; }
function markPayload(payload, originalDoc) { if (!payload || !isObject(payload)) return payload; payload.stagedJsonSource = originalDoc; if (payload.manifest) payload.manifest.source = { ...(payload.manifest.source || {}), format: 'RVM_STAGEDJSON_SOURCE_PREVIEW', stagedJsonSchema: String(originalDoc?.schema || originalDoc?.schemaVersion || '') }; if (payload.gltf?.scene?.userData) { payload.gltf.scene.userData.__rvmStagedJsonOriginalSource = originalDoc; payload.gltf.scene.userData.__rvmStagedJsonLoadAdapter = VERSION; } return payload; }
export function installRvmStagedJsonLoadAdapterBridge() { if (globalThis[INSTALL_FLAG] && globalThis[GLOBAL_KEY]) return globalThis[GLOBAL_KEY]; globalThis[INSTALL_FLAG] = true; const proto = AvevaJsonLoader?.prototype; if (!proto || typeof proto.load !== 'function') return null; if (!proto[PATCH_FLAG]) { const originalLoad = proto.load; proto.load = async function stagedJsonAwareLoad(jsonData, ctx, asyncSession) { if (!isStagedJsonDocument(jsonData)) return originalLoad.call(this, jsonData, ctx, asyncSession); const hierarchy = convertStagedJsonToAvevaHierarchy(jsonData); const payload = await originalLoad.call(this, hierarchy, ctx, asyncSession); return markPayload(payload, jsonData); }; proto[PATCH_FLAG] = { version: VERSION, patchedAt: new Date().toISOString() }; } const api = { schema: RVM_STAGEDJSON_LOAD_ADAPTER_SCHEMA, version: VERSION, isStagedJsonDocument, convertStagedJsonToAvevaHierarchy, patched: true }; globalThis[GLOBAL_KEY] = api; return api; }
